"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { GxIcon, type GxIconName } from "@growx/ui";
type NavItem = { id:string; label:string; href:string; icon:GxIconName; metadata?:string };
type NavSection = { id:string; label?:string; items:NavItem[] };
const navigation:NavSection[]=[
 {id:"overview",items:[{id:"overview",label:"Overview",href:"/admin",icon:"home"}]},
 {id:"platform",label:"Platform",items:[{id:"organizations",label:"Organizations",href:"/admin/organizations",icon:"organization"},{id:"workspaces",label:"Workspaces",href:"/admin/workspaces",icon:"workspace"},{id:"users",label:"Users",href:"/admin/users",icon:"security"}]},
 {id:"ai-control",label:"AI Control",items:[{id:"providers",label:"Providers",href:"/admin/providers",icon:"provider"},{id:"models",label:"Models",href:"/admin/models",icon:"model"},{id:"routing",label:"Routing",href:"/admin/routing",icon:"routing"},{id:"traffic",label:"Traffic",href:"/admin/routing/traffic",icon:"usage"},{id:"capacity",label:"Capacity",href:"/admin/providers/capacity",icon:"usage"},{id:"circuits",label:"Circuits",href:"/admin/providers/circuits",icon:"critical"}]},
 {id:"security",label:"Security",items:[{id:"security-events",label:"Security events",href:"/admin/security-events",icon:"security"},{id:"audit",label:"Audit",href:"/admin/audit-events",icon:"audit"}]},
 {id:"operations",label:"Operations",items:[{id:"cache",label:"Cache",href:"/admin/cache",icon:"provider"}]},
];
function isActive(pathname:string,href:string){return href==="/admin"?pathname===href:pathname===href||pathname.startsWith(`${href}/`);}
export function AdminSidebar(){const pathname=usePathname();const[collapsed,setCollapsed]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);useEffect(()=>{setCollapsed(window.localStorage.getItem("growx:admin-sidebar")==="collapsed")},[]);useEffect(()=>{window.localStorage.setItem("growx:admin-sidebar",collapsed?"collapsed":"expanded")},[collapsed]);useEffect(()=>{setMobileOpen(false)},[pathname]);useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setMobileOpen(false)};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[]);return <><button className="ops-mobile-menu" type="button" onClick={()=>setMobileOpen(true)} aria-label="Open navigation">☰</button><aside className={`ops-sidebar${collapsed?" is-collapsed":""}${mobileOpen?" is-mobile-open":""}`} aria-label="Privileged operations navigation"><div className="ops-sidebar__brand"><Link className="ops-sidebar__brand-link" href="/admin" aria-label="GrowX AI privileged operations home"><span className="brand-mark" aria-hidden="true">G</span><span className="ops-sidebar__brand-copy"><strong>GROWX AI</strong><small>PRIVILEGED</small></span></Link><button className="ops-sidebar__collapse" type="button" onClick={()=>setCollapsed(value=>!value)} aria-label={collapsed?"Expand sidebar":"Collapse sidebar"} title={collapsed?"Expand sidebar":"Collapse sidebar"}>{collapsed?"→":"←"}</button></div><nav className="ops-sidebar__nav">{navigation.map(section=><section className="ops-nav-group" key={section.id}>{section.label?<p>{section.label}</p>:null}<div>{section.items.map(item=>{const active=isActive(pathname,item.href);return <Link className={`ops-nav-item${active?" is-active":""}`} href={item.href} key={item.id} aria-current={active?"page":undefined} title={collapsed?item.label:undefined}><GxIcon name={item.icon} size={16}/><span className="ops-nav-item__label">{item.label}</span>{item.metadata?<small>{item.metadata}</small>:null}</Link>})}</div></section>)}</nav><div className="ops-sidebar__footer"><div className="ops-environment"><span className="ops-environment__dot" aria-hidden="true"/><span><strong>PRODUCTION</strong><small>Environment</small></span></div><div className="ops-operator"><span className="ops-operator__avatar" aria-hidden="true">OP</span><span className="ops-operator__copy"><strong>Operator</strong><small>Privileged session</small></span><button type="button" aria-label="Open operator menu" title="Open operator menu">⋯</button></div></div><button className="ops-mobile-close" type="button" onClick={()=>setMobileOpen(false)} aria-label="Close navigation">×</button></aside></>}
