import type { AnchorHTMLAttributes, HTMLAttributes, ReactNode } from "react"; import { cx } from "./primitives"; import { GxIcon,type GxIconName } from "./icons"; import { IconButton, Select } from "./controls";
export function AppShell({topbar,sidebar,children}: {topbar:ReactNode;sidebar:ReactNode;children:ReactNode}){return <div className="gx-app-shell"><div className="gx-app-shell__topbar">{topbar}</div><div className="gx-app-shell__sidebar">{sidebar}</div><main className="gx-app-shell__main">{children}</main></div>}
export function Topbar({brand="GrowX AI",context,actions}: {brand?:ReactNode;context?:ReactNode;actions?:ReactNode}){return <header className="gx-topbar"><div className="gx-brand"><span aria-hidden="true">G</span><strong>{brand}</strong></div>{context?<div className="gx-topbar__context">{context}</div>:null}<div className="gx-topbar__actions">{actions?? <IconButton icon="search" label="Search"/>}</div></header>}
export function Sidebar(props:HTMLAttributes<HTMLElement>){return <aside {...props} className={cx("gx-sidebar",props.className)}/>} 
export function SidebarGroup({label,children}: {label:string;children:ReactNode}){return <section className="gx-sidebar-group"><h2>{label}</h2><div>{children}</div></section>}
export function SidebarItem({icon,label,active=false,...props}:AnchorHTMLAttributes<HTMLAnchorElement>&{icon?:GxIconName;label:string;active?:boolean}){return <a {...props} aria-current={active?"page":undefined} className={cx("gx-sidebar-item",active&&"gx-sidebar-item--active",props.className)}>{icon?<GxIcon name={icon}/>:null}<span>{label}</span></a>}
export function Breadcrumb({items}: {items:Array<{label:string;href?:string}>}){return <nav className="gx-breadcrumb" aria-label="Breadcrumb"><ol>{items.map((item,index)=><li key={`${item.label}-${index}`}>{item.href?<a href={item.href}>{item.label}</a>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>}
export function Tabs({label="Sections",children}: {label?:string;children:ReactNode}){return <div className="gx-tabs" role="tablist" aria-label={label}>{children}</div>}
export function Tab({active=false,children,onClick}: {active?:boolean;children:ReactNode;onClick?:()=>void}){return <button className="gx-tab" role="tab" type="button" aria-selected={active} tabIndex={active?0:-1} onClick={onClick}>{children}</button>}
export function Pagination({page=1,pages=1,onPageChange}: {page?:number;pages?:number;onPageChange?:(page:number)=>void}){return <nav className="gx-pagination" aria-label="Pagination"><button type="button" disabled={page<=1} onClick={()=>onPageChange?.(page-1)}>Previous</button><span aria-live="polite">Page {page} of {pages}</span><button type="button" disabled={page>=pages} onClick={()=>onPageChange?.(page+1)}>Next</button></nav>}
export function CommandPalette({open=true,children}: {open?:boolean;children?:ReactNode}){return open?<section className="gx-command" role="dialog" aria-modal="true" aria-label="Command palette"><header><GxIcon name="search"/><input autoFocus={false} placeholder="Search GrowX…" aria-label="Search commands"/></header><div>{children??<><button type="button"><GxIcon name="playground"/>Open Playground <kbd>G P</kbd></button><button type="button"><GxIcon name="log"/>View gateway logs <kbd>G L</kbd></button></>}</div></section>:null}
export function ContextSwitcher({label,value,options}: {label:string;value:string;options:string[]}){return <label className="gx-context-switcher"><span>{label}</span><Select defaultValue={value}>{options.map(option=><option key={option}>{option}</option>)}</Select></label>}
export const OrganizationSwitcher=(props:{value:string;options:string[]})=><ContextSwitcher label="Organization" {...props}/>; export const WorkspaceSwitcher=(props:{value:string;options:string[]})=><ContextSwitcher label="Workspace" {...props}/>; export const EnvironmentSwitcher=(props:{value:string;options:string[]})=><ContextSwitcher label="Environment" {...props}/>;
