import type { ReactNode } from "react"; import { PageHeader,Toolbar } from "./surfaces";
type TemplateProps={header:ReactNode;children:ReactNode};
export function ResourceListTemplate({header,toolbar,children,pagination}:TemplateProps&{toolbar:ReactNode;pagination?:ReactNode}){return <div className="gx-template gx-template--list"><div>{header}</div><Toolbar>{toolbar}</Toolbar><div>{children}</div>{pagination?<footer>{pagination}</footer>:null}</div>}
export function ResourceDetailTemplate({breadcrumb,header,metadata,tabs,children}:TemplateProps&{breadcrumb:ReactNode;metadata:ReactNode;tabs:ReactNode}){return <div className="gx-template gx-template--detail">{breadcrumb}<div>{header}</div><div className="gx-template__metadata">{metadata}</div>{tabs}<div>{children}</div></div>}
export function DashboardTemplate({header,metrics,panels,activity}: {header:ReactNode;metrics:ReactNode;panels:ReactNode;activity:ReactNode}){return <div className="gx-template gx-template--dashboard">{header}<div className="gx-template__metrics">{metrics}</div><div className="gx-template__panels">{panels}</div><div>{activity}</div></div>}
export function SettingsTemplate({navigation,header,children}:TemplateProps&{navigation:ReactNode}){return <div className="gx-template gx-template--settings"><aside>{navigation}</aside><main>{header}{children}</main></div>}
export function LogsTemplate({header,filters,table,inspector}: {header:ReactNode;filters:ReactNode;table:ReactNode;inspector?:ReactNode}){return <div className="gx-template gx-template--logs">{header}<Toolbar>{filters}</Toolbar>{table}{inspector}</div>}
export function PlaygroundTemplate({header,model,input,output,metadata}: {header:ReactNode;model:ReactNode;input:ReactNode;output:ReactNode;metadata:ReactNode}){return <div className="gx-template gx-template--playground">{header}<div>{model}</div><div className="gx-template__playground-panes">{input}{output}</div><footer>{metadata}</footer></div>}
export function BillingTemplate({header,balance,usage,invoices,settings}: {header:ReactNode;balance:ReactNode;usage:ReactNode;invoices:ReactNode;settings:ReactNode}){return <div className="gx-template gx-template--billing">{header}<div className="gx-template__billing-summary">{balance}{usage}</div>{invoices}{settings}</div>}
export function PrivilegedOperationsTemplate({context,header,controls,data,inspector}: {context:ReactNode;header:ReactNode;controls:ReactNode;data:ReactNode;inspector?:ReactNode}){return <div className="gx-template gx-template--ops"><div className="gx-template__plane">{context}</div>{header}<Toolbar>{controls}</Toolbar>{data}{inspector}</div>}
export function AnalyticsTemplate({header,metrics,chart,table}: {header:ReactNode;metrics:ReactNode;chart:ReactNode;table:ReactNode}){return <DashboardTemplate header={header} metrics={metrics} panels={chart} activity={table}/>}
export function TemplateHeader({title,description,actions}: {title:string;description:string;actions?:ReactNode}){return <PageHeader title={title} description={description} actions={actions}/>}
