import styles from "./all.module.css";

const library = [
  {href:"/design/colors",number:"00",title:"Colors",detail:"Obsidian, Frost, GrowX Ice, and operational semantics",icon:"model",items:["Raw palette","Semantic mapping","Contrast pairs"]},
  {href:"/design/typography",number:"01",title:"Typography",detail:"Manrope UI and JetBrains Mono developer language",icon:"code",items:["Type scale","Numerals","Code"]},
  {href:"/design/icons",number:"02",title:"GrowX icons",detail:"Complete geometric baseline icon family",icon:"workspace",items:["Navigation","Infrastructure","Actions","Status"]},
  {href:"/design/buttons",number:"03",title:"Buttons",detail:"Neutral-first actions across every size and state",icon:"more",items:["Primary","Secondary","Ghost","Danger","Link","Icon"]},
  {href:"/design/forms",number:"04",title:"Form controls",detail:"Accessible 38px product inputs and field structures",icon:"filter",items:["Inputs","Selects","Choices","Switches","Slider","Segments"]},
  {href:"/design/status",number:"05",title:"Status",detail:"Semantic indicators that never rely on color alone",icon:"check",items:["Badge","Chip","Pill","Dot","Health","Progress","Meter"]},
  {href:"/design/navigation",number:"06",title:"Navigation",detail:"Tenant context and grouped product hierarchy",icon:"routing",items:["Shell","Topbar","Sidebar","Tabs","Breadcrumb","Command"]},
  {href:"/design/cards",number:"07",title:"Surfaces",detail:"Quiet containment for operational information",icon:"home",items:["Cards","Panels","Metrics","Callouts","Banners","Inspector"]},
  {href:"/design/tables",number:"08",title:"Tables & data",detail:"Dense infrastructure data and technical identifiers",icon:"log",items:["Table","Data table","Toolbar","Pagination","Row actions"]},
  {href:"/design/overlays",number:"09",title:"Overlays",detail:"From tooltips to 720px technical flyouts",icon:"environment",items:["Tooltip","Dropdown","Popover","Flyout","Sheet","Modal","Toast"]},
  {href:"/design/developer",number:"10",title:"Developer surfaces",detail:"Code, requests, responses, keys, and streaming",icon:"terminal",items:["Code","JSON","Inspector","API key","Playground","Streaming"]},
  {href:"/design/charts",number:"11",title:"Charts",detail:"Ice-led operational visualization without rainbow noise",icon:"usage",items:["Line","Area","Bar","Stacked","Donut","Sparkline","Heatmap"]},
  {href:"/design/motion",number:"12",title:"Motion",detail:"Quiet 120–280ms interaction timing",icon:"playground",items:["Fast","Standard","Overlay","Large","Reduced motion"]},
  {href:"/design/templates",number:"13",title:"Components & templates",detail:"Domain assemblies and every approved page pattern",icon:"organization",items:["Domain","Feedback","Resource","Dashboard","Logs","Billing","Ops"]},
] as const;

export default function Page(){return <main className={`gx-design-library ${styles.page}`}><header className={styles.hero}><div className={styles.brand}><span>G</span><strong>GrowX AI</strong></div><p>Coded Figma-equivalent library</p><h1>The complete system, in one architecture.</h1><footer><b>Foundation library</b><span>14 canonical references</span><span>Reusable @growx/ui exports</span></footer></header><section className={styles.foundation}><header><span>FOUNDATION CONTRACT</span><strong>One source of truth</strong></header><div>{["Colors","Typography","Spacing","Grid","Layout","Breakpoints","Radii","Borders","Shadows","Motion","Z-index","Focus","Accessibility","Scrollbars","Selection","Surfaces"].map(item=><span key={item}><i/>{item}</span>)}</div></section><section className={styles.grid} aria-label="Design library references">{library.map(group=><a href={group.href} key={group.href}><header><span>{group.number}</span><i aria-hidden="true"/></header><h2>{group.title}</h2><p>{group.detail}</p><div>{group.items.map(item=><span key={item}>{item}</span>)}</div><footer>Open canonical reference <b aria-hidden="true">›</b></footer></a>)}</section><footer className={styles.gate}><div><span>DESIGN SYSTEM GATE</span><strong>Library architecture implemented</strong></div><p>Feature pages remain separate from this source of truth until the existing UI refactor gate is explicitly started.</p></footer></main>}
